title: Mickael Dias
description:
  ◼️ Sciences and Technology Student from ESF
  ◼️ Arch Linux Power User
profile_pic: https://instagram.fopo2-2.fna.fbcdn.net/t51.2885-19/s320x320/20837809_714098512132283_917343291450589184_a.jpg
show_downloads: false
twitter: https://twitter.com/llamakorn_boy
google_analytics:
theme: jekyll-theme-minimal